name: MinecraftPluginCursor
version: '${project.version}'
main: com.example.mcplugincursor.MinecraftPluginCursor
api-version: '1.20'
description: A simple hello world plugin for Minecraft
author: YourName 